<a href="https://colab.research.google.com/github/hsnvsherif/Linked-List/blob/main/_Matrix_Inversionbyformula.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Define the matrix M
M = np.array([[2, 0, 1], [0, 1, 0], [1, 2, 0]])

# Calculate the determinant of M
det_M = np.linalg.det(M)

# If determinant is not zero, calculate the inverse
if det_M != 0:
    inverse_M = np.linalg.inv(M)
else:
    inverse_M = "Matrix is not invertible"

# Print results
print("Determinant of M:", det_M)
print("Inverse of M:")
print(inverse_M)

# Define the matrix A
A = np.array([[4, -3, 7], [-1, 6, 3], [2, 9, 1]])

# Calculate the determinant of A
det_A = np.linalg.det(A)

# Determine the rank of A
rank_A = np.linalg.matrix_rank(A)

# Print results
print("Determinant of A:", det_A)
print("Rank of A:", rank_A)


Determinant of M: -1.0
Inverse of M:
[[ 0. -2.  1.]
 [ 0.  1.  0.]
 [ 1.  4. -2.]]
Determinant of A: -251.9999999999998
Rank of A: 3
